baseURL = "https://bullish-intelligence.github.io/"
title = "Bullish Intelligence"
languageCode = "en-us"

# We're using Hugo Modules to pull in the custom Roxo theme.
[module]
  # Direct mode is important when using private GitHub repos for modules.
  proxy = "direct"

  [module.hugoVersion]
    extended = true
    min = "0.120.0"

  # Import your custom Roxo fork as a module.
  [[module.imports]]
    path = "github.com/bullish-intelligence/roxo-muted"

